### ISSUE TITLE
OS X 10.11 El Capitan support

### ISSUE THREAD

**Issue by gunta** [TeamAntumbra/mactumbra#2]
Hi!

I am using OS X 10.11 El Capitan latest beta and mactumbra doesn't seem to work.
Is there any plan to support it?

**Comment by thedriveman** [comment]
Same here, not working on El Capitan Beta 5. 
El Capitan may be released in couple of weeks on the Sep 9th event. Would appreciate if you can take a look into it.

**Comment by qwertyflagstop** [comment]
Yes! We plan to fully support it. The next major update will be a fix along with some new features for multi-unit setups.

**Comment by thedriveman** [comment]
Current release on MBP 15, El Capitan and 4K Dell monitor doesn't work. LED is stuck on green and the app doesn't seem to control it.

**Comment by alexchastan** [comment]
I've just receive my Antumbra but i have the same problem on Mac OS El Capitan : the LED is stuck on green. Is there any news about a release date please ?

**Comment by gunta** [comment]
Yeah. A roadmap will be enough to keep everyone happy.

Because if it takes too much time the community just might try to make it
work before that.

On Wed, Oct 14, 2015 at 3:39 PM, Alexandre CHASTAN <notifications@github.com

**Comment by vicwork** [comment]
Still waiting.  Any plans?

**Comment by patricksanders** [comment]
Both 1.0 and 1.01 work for me in OS X 10.11.2. Good work!

**Comment by walshie4** [comment]
Should be fixed quite soon now that libusb has been fixed (Apple silently broke it with 10.11).

https://github.com/libusb/libusb/issues/127

**Comment by walshie4** [comment]
Actually, already fixed. Will be in the next release.

https://github.com/TeamAntumbra/mactumbra/commit/a23c4b1d7515f9af0da72ef24970aa940627364f

Also relevant https://github.com/TeamAntumbra/antumbra-deps/commit/608f17549bbbdf256b718b6d778908c4791b7f32

**Comment by qwertyflagstop** [comment]
Release is up.
